all:
	echo mjqjpqmgbljsphdztnvjfqwrcgsmlb | ./puzzle.py 7 19
	echo bvwbjplbgvbhsrlpgdmjqwftvncz | ./puzzle.py 5 23
	echo nppdvjthqldpwncqszvftbrmjlhg | ./puzzle.py 6 23
	echo nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg | ./puzzle.py 10 29
	echo zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw | ./puzzle.py 11 26
	cat input | ./puzzle.py
